kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane  
  extraMounts: 
  - hostPath: "/home/albee/Documents/GitHub/k8s-swarm-optimization/colony-controller/logs"
    containerPath: /mycolony




