apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: colony-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeName: colony-pv
